= Prefácio 

== Sobre i-Educar

O i-Educar é um software livre de gestão escolar totalmente on-line que
permite secretários escolares, professores, coordenadores e gestores da
área possam utilizar uma ferramenta que produz informações e
estatísticas em tempo real, com um banco de dados centralizado e de
fácil acesso, diminuindo a necessidade de uso de papel, a duplicidade de
documentos, o tempo de atendimento ao cidadão e racionalizando o
trabalho do servidor público.

Ele foi originalmente desenvolvido pela prefeitura de Itajaí - SC e
disponibilizado no Portal do Software Público do Governo Federal em
2008, com o objetivo de atender às necessidades das Secretarias de
Educação e Escolas Públicas de *todo o Brasil*.

== Comunicação

Acreditamos que o sucesso do projeto depende diretamente da interação
clara e objetiva entre os membros da Comunidade. Por isso, estamos
definindo algumas políticas para que estas interações nos ajudem a
crescer juntos! Você pode consultar algumas destas boas práticas em
nosso
https://github.com/portabilis/i-educar/blob/master/code-of-conduct.md[código
de conduta].

Além disso, gostamos de meios de comunicação assíncrona, onde não há
necessidade de respostas em tempo real. Isso facilita a produtividade
individual dos colaboradores do projeto.

[width="100%",cols="67%,33%",options="header",]
|===
|Canal de comunicação |Objetivos
|https://forum.ieducar.org[Fórum] |- Tirar dúvidas - Discussões de como
instalar a plataforma - Discussões de como usar funcionalidades -
Suporte entre membros de comunidade - FAQ da comunidade (sobre o produto
e funcionalidades)

|https://github.com/portabilis/i-educar/issues/new/choose[Issues do
Github] |- Sugestão de novas funcionalidades - Reportar bugs -
Discussões técnicas

|https://t.me/ieducar[Telegram] |- Comunicar novidades sobre o projeto -
Movimentar a comunidade - Falar tópicos que *não* demandem discussões
profundas
|===

Qualquer outro grupo de discussão não é reconhecido oficialmente pela
comunidade i-Educar e não terá suporte da Portabilis - mantenedora do
projeto.

== Como contribuir

Contribuições são *super bem vindas*! Se você tem vontade de construir o
i-Educar junto conosco, veja o nosso link:./contributing.md[guia de
contribuição] onde explicamos detalhadamente como trabalhamos e de que
formas você pode nos ajudar a alcançar nossos objetivos.

== Perguntas frequentes (FAQ)

=== Qual é o modelo de governança do i-Educar?

Atualmente o projeto é mantido pela
http://www.portabilis.com.br/[Portabilis], empresa que fornece serviços
de implantação, implementação e manutenção do i-Educar em dezenas de
municípios espalhados pelo Brasil. A Portabilis também é responsável
pela grande maioria dos commits no projeto, colaborando com novos
recursos, correção de bugs, etc.

Apesar do i-Educar já existir como código aberto a muitos anos, sua
estruturação como um projeto open-source ativo é algo recente e por isso
ainda não existe um modelo de governança estabelecido. Por hora a
Portabilis e seus membros e parceiros são responsáveis pela definição do
roadmap, moderação das discussões e aplicação de patches. Esperamos
contar cada vez mais com a participação da comunidade nestes aspectos.

=== Como ajudar o i-Educar a ter um fluxo de trabalho mais aberto e transparente em comunidade?

Recentemente a Portabilis se dispôs a trabalhar diretamente com o
i-Educar em comunidade. Por causa disto foi feita uma contribuição
imensa de melhorias e recursos ao projeto dando origem à versão 2.0 do
sistema. Melhorias estas que antes vinham sendo desenvolvidas em um fork
interno. Sendo assim, a própria mantenedora ainda está em processo de se
adequar a esta nova forma de trabalho e o fluxo ainda precisa de
ajustes.

Foi proposto um
https://github.com/portabilis/i-educar/projects/3[roadmap] e nosso foco
tem sido em executá-lo, de forma que o melhor jeito de ajudar é se
engajando de forma mais incisiva naquilo que é prioritário de acordo com
o próprio roadmap. Aos poucos vamos ajustando nossos fluxos de trabalho
para que sejam totalmente transparentes e contamos com o auxílio e
paciência de todos os membros da comunidade durante este processo.

=== Seria possivel incluir algum membro de comunidade na administração do projeto?

Antes de tudo é importante deixar claro que a Portabilis, na forma de
pessoas que trabalham ativamente no i-Educar, é um membro da comunidade
como qualquer outro. Um membro que contribuiu com mais de 10.000 commits
em melhorias e bug fixes, incluindo o censo escolar que é revolucionário
para gestão escolar. Acreditamos que com este trabalho a Portabilis
mereceu seu posicionamento como mantenedora do projeto.

Da mesma forma acreditamos que qualquer outro membro da comunidade que
possa vir a se tornar administrador do projeto deva merecer esta
posição, ou seja, não iremos indicar um segundo ou terceiro membro da
comunidade para administração por uma questão meramente política, mas
sim por uma questão prática de envolvimento e dedicação ao projeto.

De qualquer forma, esperamos que o engajamento de qualquer pessoa na
comunidade não dependa da possibilidade de se obter títulos ou posições
dentro do projeto.

== Como é o desenvolvimento

Planejamento sugerido por
[@diegoholiveira](https://github.com/diegoholiveira) e que deve ser o
caminho que seguiremos. Abriremos discussão em breve sobre o assunto.

=== 1) Adotar padrões:

* PSR-1 e PSR-2 como coding style;
* PSR-4 para organização do código;

Pensando nisso, iriamos migrar todas as classes e interfaces para uma
pasta `src` na raiz do projeto. Todos os arquivos públicos iriam para a
pasta `public` e apenas essa pasta deveria ser visível no servidor web.
Todos os `require` e `include` seriam excluídos e apenas o autoload do
composer seria usado pra carregar as classes e outras dependências.

Essa primeira parte iria preparar nosso código para as mudanças futuras.

=== 2) Separar o HTML do PHP

Remover todo o html / css / javascript que estiver na pasta `src`. os
assets (css/javascript), inicialmente vão pra pasta `public`. O HTML
deve ser extraído para uma pasta chamada `templates` e renderizado
usando o https://twig.symfony.com[Twig].

Isso iria começar a separar a camada de template do nosso código, assim
mudanças de UI não precisam ser feitas no código e nosso código para a
ficar mais limpo, para que as próximas mudanças sejam mais fáceis.

=== 3) Adotar o Symfony como framework;

Inicialmente começamos implementando apenas o roteamento de urls pra
dentro do Symfony, sem nos preocupar em usar todo o poderio do Symfony,
como DI e outras coisas; Com o tempo vamos refatorando o código pra usar
todo o poderio do Symfony.

=== 4) Adotar uma ORM

Como Symfony não define um ORM padrão, poderiamos adotar qualquer bom
ORM disponível. Eu recomendo o Doctrine, é um projeto muito maduro e que
funciona muito bem.

=== 5) Adotar webpack e começar a transformar o sistema em um Single Page Application;

Nessa fase poderiamos adotar react / vue ou outro framework pra front
end e começariamos a transformar o código php pra servir JSON ao invés
de HTML;
