= Capítulo 01 - Instalação

== Pre requisitos

* http://php.net/[PHP] versão 7.4
* https://getcomposer.org/[Composer]
* https://www.postgresql.org/[Postgres]
* https://www.nginx.com/[Nginx]
* https://redis.io/[Redis]

As seguintes extensões do PHP são necessárias:

* bcmath
* ctype
* curl
* dom
* fileinfo
* gd
* iconv
* json
* libxml
* mbstring
* openssl
* pcre
* PDO
* pgsql
* Phar
* SimpleXML
* tokenizer
* xml
* xmlreader
* xmlwriter
* zip
* zlib

O i-Educar possui um instalador que pode te auxiliar no processo de
instalação em um servidor para produção.

Antes de tudo faça
https://github.com/portabilis/i-educar/releases[download] da versão mais
recente do i-Educar e extraia o conteúdo do release em uma pasta no seu
servidor. O instalador está disponível desde a versão `2.1.0`.

Instale pela sua distribuição o `php` (na versão 7.4 ou superior),
o `git`, o `nginx` e o `postgresql` (na versão 13). Na sequencia extraia
os códigos fontes do i-Educar para o diretório `/var/www/ieducar`

== Configurando o servidor

O *Nginx* precisa estar devidamente configurado para rodar o i-Educar e
permitir acesso ao instalador. Você encontra um exemplo de configuração
https://github.com/portabilis/i-educar/blob/master/docker/nginx/default.conf[aqui].

Em sistemas *Ubuntu*, por exemplo, você colocaria este arquivo na pasta
`/etc/nginx/sites-available` e criaria um symlink para ele na pasta
`/etc/nginx/sites-enabled`.

Não esqueça de adequar a configuração de acordo com a realidade do seu
servidor principalmente as seguintes diretivas:

* `root`
* `fastcgi_pass`

Depois de tudo pronto basta reiniciar o processo do nginx para que as
configurações novas entrem em vigor.

== Executando o instalador

Agora que o Nginx está configurado você pode acessar o instalador em:

....
http://www.example.com/install.php
....

Substitua ``www.example.com'' pelo seu domínio ou endereço de IP. A
partir daqui o instalador deverá te dar todas as instruções necessárias
para realizar a instalação com sucesso. Todo exemplo de comando ou
código que possa vir a aparecer no processo de instalação leva em
consideração o seu ambiente, ou seja, fique à vontade para copiar e
colar os comandos que eles deverão funcionar corretamente.

Quando tudo estiver ok você poderá definir uma senha para o usuário
`admin` e iniciar o processo de instalação. Se tudo correr bem você
poderá acessar o i-Educar normalmente.

Em caso de erros no processo de instalação verifique os logs do sistema
que se encontram em `storage/logs` para determinar suas causas. Não
hesite em link:#comunicação[entrar em contato] caso enfrente
dificuldades!

== Instalação do pacote de relatórios

O i-Educar possui um pacote de mais de 40 relatórios.

Para instalar o pacote de relatórios visite o repositório do projeto
https://github.com/portabilis/i-educar-reports-package e siga as
instruções de instalação.

== Upgrade

* https://github.com/portabilis/i-educar/wiki/Upgrade-para-2.6-da-2.5[Upgrade
para 2.6 da 2.5].
* https://github.com/portabilis/i-educar/wiki/Upgrade-para-2.5-da-2.4[Upgrade
para 2.5 da 2.4].
* https://github.com/portabilis/i-educar/wiki/Upgrade-para-2.4-da-2.3[Upgrade
para 2.4 da 2.3].
* https://github.com/portabilis/i-educar/wiki/Upgrade-para-2.3-da-2.2[Upgrade
para 2.3 da 2.2].
* https://github.com/portabilis/i-educar/wiki/Upgrade-para-2.2-da-2.1[Upgrade
para 2.2 da 2.1].
* https://github.com/portabilis/i-educar/wiki/Upgrade-para-2.1-da-2.0[Upgrade
para 2.1 da 2.0].
