=  CapInstalação para desenvolvedores

== Dependência

Para executar o projeto é necessário a utilização de alguns softwares
para facilitar o desenvolvimento.

== Instalação utilizando Docker

WARNING: Essa forma de instação tem o objetivo de facilitar
demonstrações e desenvolvimento. Não é recomendado para ambientes de
produção!

Para instalar o projeto execute *todos os passos* abaixo, caso você
deseje atualizar sua instalação do i-Educar, siga os passos do
link:#upgrade[upgrade].

Clone o repositório:

[source,bash]
----
git clone https://github.com/portabilis/i-educar.git && cd i-educar
----

Faça o build das imagens Docker utilizadas no projeto (pode levar alguns
minutos) e inicie os containers da aplicação:

[source,bash]
----
docker-compose up -d --build
----

Execute o comando para fazer uma nova instalação:

[source,bash]
----
docker-compose exec php composer new-install
----

== Primeiro acesso

Após finalizada a instalação, descubra em qual endereço o i-Educar está
rodando, basta executar o comando:

[source,bash]
----
docker-compose port nginx 80
----

Acesse o endereço que será exibido após rodar o comando acima.

O usuário padrão é: `admin` / A senha padrão é: `123456789`

Assim que realizar seu primeiro acesso *não se esqueça de alterar a
senha padrão*.

== Personalizando a instalação

Você pode criar um arquivo `docker-compose.override.yml` para
personalizar sua instalação do i-Educar, mudando as portas dos serviços
ou o mapeamento dos volumes extras para a aplicação.

== Executando testes unitários

Para rodar os testes, é necessário ter o i-Educar rodando e com uma base
limpa, apenas a estrutura inicial e as migrations, crie o arquivo de
configuração:

[source,bash]
----
cp .env.example .env.testing
----

Execute o comando:

[source,bash]
----
docker-compose exec php vendor/bin/phpunit
----

== Xdebug

A ferramenta https://xdebug.org/[Xdebug] está incluída no projeto com o
intuito de facilitar o processo de debug durante o desenvolvimento. Para
configurá-la, modifique os valores das variáveis `XDEBUG_*` no arquivo
`docker-compose.override.yml` conforme orientações da sua IDE de
desenvolvimento.
